### ISSUE TITLE
Radio scrobbling

### ISSUE THREAD

**Issue by hosswald** [valentin-gosselin/lastfm-scrobbler-ha-integration#3]
It would be nice to be able to scrobble radio stations as well.
[As mentioned in the HA forums](https://community.home-assistant.io/t/lastfm-scrobbler-integration/624390/5?u=hosswald), I'm getting the following error:
```
Unexpected type for last_updated_at: <class 'NoneType'>
Source: custom_components/lastfm_scrobbler/media_player.py:81
```
Here are the status attributes for my media player (removed irrelevant entries):
```yaml
volume_level: 0.23
is_volume_muted: false
media_content_id: ...
media_content_type: music
media_title: <Title>
media_artist: <Artist>
media_album_name: ""
source: <Name of the radio station>
media_album_id: <Album>
media_queue_id: 1
media_source_id: 3
media_station: <Name of the radio station>
media_type: station
media_duration: 0
```
`media_duration` remains `0` all the time while listening to a radio station.
There is no `media_position` or `media_position_updated_at`...
I guess `media_type: station` would be a good condition to check if we're in radio mode.
