### ISSUE TITLE
[Feature Request] do not scrobble if attribute "app_name" of a media_player entity is in denylist

### ISSUE THREAD

**Issue by I-G-1-1** [valentin-gosselin/lastfm-scrobbler-ha-integration#6]
Could be possible to implement a denylist for specific "app_name" or "app_id" attributes of a "media_player" to avoid scrobbling for that specific "app_name"?

I'm trying to avoid double scrobbling when I cast from my phone to my google home device (integrated in Home Assistant).

I'm using "Pano Scrobbler" on my Android phone with the player "Symfonium".

When I cast from my phone to my google home device both "Pano Scrobbler" and "lastfm-scrobbler-ha-integration" report the song to lastfm and it ends with songs scrobbled 2 times.

I cannot disable "Pano Scrobbler" as I need it to scrobble when I listen the music on my phone.
I cannot disable "lastfm-scrobbler-ha-integration" as I need it when I listen music using MusicAssistant.

I noticed that the "media_player" entity has attributes that indicate the source of the streaming:
```
device_class:
friendly_name:
supported_features:
volume_level:
is_volume_muted: false
media_content_type: music
app_id:                                   <-------------
app_name:                                 <-------------
entity_picture_local:
media_position_updated_at:
media_content_id:
media_position:
media_title:
media_artist:
media_album_name:
media_album_artist:
entity_picture:
media_duration:
```

My feature request is to add in the configuration of "lastfm-scrobbler-ha-integration" the ability to add specific "app_name" so if the current attribute "app_name" in the media_player entity matches one in the denylist the integration won't scrobble.

Thanks

**Comment by retpolanne** [comment]
+1, I keep getting YouTube videos to show up on my Last.fm due to my Apple TV being connected

**Comment by I-G-1-1** [comment]
version 1.3.0 implemented check_entities that allows scrobbling only if an entity person/switch/Input_booleans return a positive value.

using this new feature with the help of a template and some automations I could avoid to scrobble If the source app of the media_player entity is "Symfonium" (or any other app) and avoid double scrobbling when I cast from my phone to my google home device.

```
input_boolean:
  media_player_source_is_not_symfonium_or_other_android_apps:
    name: "Media Player source is not Symfonium or other Android apps"
    icon: mdi:toggle-switch-outline

template:
  - binary_sensor:
      - name: "Media Player source is not Symfonium or other Android apps"
        unique_id: 'D381387A-75F7-4CA4-A331-C51C330CCA7E'
        state: >
          {% if is_state_attr("media_player.room_01", "app_name", "Symfonium") -%}
          false
          {% elif is_state_attr("media_player.room_02", "app_name", "Symfonium") -%}
          false
          {%- else -%}
          true
          {%- endif %}
          
automation:
  - alias: "Media Player source is not Symfonium or other Android apps set on"
    id: '537A6FA6-85EF-4387-99EA-2D586AA7D4CA'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.media_player_source_is_not_symfonium_or_other_android_apps
        from: 'off'
        to: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.media_player_source_is_not_symfonium_or_other_android_apps

  - alias: "Media Player source is not Symfonium or other Android apps set off"
    id: '97620BE8-29CC-40A0-8A74-63022237D98A'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.media_player_source_is_not_symfonium_or_other_android_apps
        from: 'on'
        to: 'off'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.media_player_source_is_not_symfonium_or_other_android_apps
```

as last thing in the "lastfm-scrobbler-ha-integration" integration configuration page in the webUI under 
`Optional: Only scrobble when ALL selected entities are "positive" (person=home, switch=on, etc.)`
add the input_boolean just created:
`input_boolean.media_player_source_is_not_symfonium_or_other_android_apps`
